# Generated by Django 5.2.6 on 2025-10-01 11:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Salary, Rent, Groceries', max_length=50)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], help_text='Choose whether this category is for Income or Expense', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short description, e.g., 'October Salary' or 'Groceries'", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount (e.g., 250.00)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], help_text='Is this an Income or an Expense?', max_length=7)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='When did this happen?')),
                ('notes', models.TextField(blank=True, help_text='Optional notes (e.g., receipt ID, details)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Pick a category that matches the transaction type', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category')),
                ('user', models.ForeignKey(help_text='Owner of this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='GBP', help_text='3-letter currency code, e.g., GBP, USD, EUR', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance (optional), used in summaries', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'name'), name='uq_category_user_type_name'),
        ),
    ]
