# Generated by Django 5.2.6 on 2025-10-02 10:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)'), ('INR', 'Indian Rupee (₹)'), ('CAD', 'Canadian Dollar ($)'), ('AUD', 'Australian Dollar ($)'), ('JPY', 'Japanese Yen (¥)')], default='GBP', help_text='3-letter currency code, e.g., GBP, USD, EUR', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance (optional), used in summaries', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
