"""
Django settings for mo4_tracker project (simple, MySQL version).
Generated by 'django-admin startproject' using Django 5.2.6.

This file is intentionally simple so it’s easy to read and learn from.
"""

# ✅ Path handling (used to build absolute file-system paths like BASE_DIR / "templates")
from pathlib import Path

# ✅ Optional now, handy later if you decide to read environment variables
import os

# ✅ BASE_DIR points to the folder that contains manage.py
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------
# 🔐 SECURITY / DEBUG (DEV)
# ---------------------------

# ✅ SECRET_KEY is required by Django; OK to hardcode for local learning
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-change-me")

# ✅ DEBUG=True shows detailed error pages; keep True in development only
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# ✅ Hosts that can serve this app; for local dev, these two are enough
ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")]


CSRF_TRUSTED_ORIGINS = [
    os.environ.get("DJANGO_CSRF_ORIGIN", "http://localhost")
]
# ---------------------------
# ✅ INSTALLED APPS (core)
# ---------------------------

# ✅ Default Django apps we need right now (we will add our app in Phase 1)
INSTALLED_APPS = [
    "django.contrib.admin",            # Admin site
    "django.contrib.auth",             # Authentication
    "django.contrib.contenttypes",     # Content types framework
    "django.contrib.sessions",         # Sessions
    "django.contrib.messages",         # Flash messages
    "django.contrib.staticfiles",      # Static files (CSS/JS/images)
    "finance",                        # ✅ our app for categories, transactions, user profile
    "accounts.apps.AccountsConfig",   # ✅ new app for auth pages

]


# ---------------------------
# ✅ AUTH FLOW SETTINGS
# ---------------------------

# ✅ After login, send the user to a simple “home” page (we’ll create it below)
LOGIN_REDIRECT_URL = "accounts:home"   # name of a URL pattern we’ll define

# ✅ If someone hits a @login_required view, send them here to log in
LOGIN_URL = "accounts:login"

# ✅ After logout, send them back to login screen
LOGOUT_REDIRECT_URL = "accounts:login"

# ✅ For password reset in development, send emails to the console (no real email needed)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"









# ---------------------------
# ✅ MIDDLEWARE (leave default)
# ---------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",           # Basic security
    "django.contrib.sessions.middleware.SessionMiddleware",    # Session support
    "django.middleware.common.CommonMiddleware",               # Common HTTP helpers
    "django.middleware.csrf.CsrfViewMiddleware",               # CSRF protection
    "django.contrib.auth.middleware.AuthenticationMiddleware", # Auth attaches user to request
    "django.contrib.messages.middleware.MessageMiddleware",    # Messages framework
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking protection
]


# ---------------------------
# ✅ URLS / WSGI
# ---------------------------

# ✅ Root URLconf module (mo4_tracker/urls.py)
ROOT_URLCONF = "mo4_tracker.urls"

# ✅ Templates configuration (where Django finds your HTML)
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",  # Django template engine
        "DIRS": [BASE_DIR / "templates"],                              # Global templates folder (create later)
        "APP_DIRS": True,                                              # Also use each app’s /templates
        "OPTIONS": {
            "context_processors": [                                    # Extra variables available in templates
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ✅ WSGI entrypoint (used by production servers; fine as default)
WSGI_APPLICATION = "mo4_tracker.wsgi.application"


# ---------------------------
# ✅ DATABASE (MySQL)
# ---------------------------

# 🔎 Requirements:
#   1) MySQL server running on 127.0.0.1:3306
#   2) Database already created: trackerdb
#   3) Valid user/password (root/root here is just an example — replace with yours)
#   4) Install driver: pip install mysqlclient
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",                     # ← MySQL backend
        "NAME": os.environ.get("DB_NAME", "trackerdb"),           # ← DB name
        "USER": os.environ.get("DB_USER", "root"),                # ← DB user
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),            # ← DB password
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),           # ← DB host
        "PORT": os.environ.get("DB_PORT", "3306"),                # ← default port
        "OPTIONS": {
            "charset": "utf8mb4",                                 # ← full Unicode
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'", # ← strict mode
        },
        "CONN_MAX_AGE": 60,                                       # ← keep-alive
    }
}


# ---------------------------
# ✅ PASSWORD VALIDATION
# ---------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ---------------------------
# ✅ I18N / TIMEZONE
# ---------------------------

# ✅ UK-friendly formatting; Django stores datetimes in UTC internally
LANGUAGE_CODE = "en-gb"
TIME_ZONE = "Europe/London"
USE_I18N = True
USE_TZ = True


# ---------------------------
# ✅ STATIC FILES
# ---------------------------

# ✅ URL prefix for static files (CSS/JS/images)
STATIC_URL = "static/"

# ✅ Optional: where your local static source files live during development
#    (Create this folder later when you add CSS/JS)
STATICFILES_DIRS = [BASE_DIR / "static"]

# ---------------------------
# ✅ DEFAULT AUTO FIELD
# ---------------------------

# ✅ Use BigAutoField for primary keys (modern default)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
